//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bike_Store_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int store_id { get; set; }
        public string store_name { get; set; }
        public int product_id { get; set; }

        public Nullable<int> quantity { get; set; }
    
        public  product product { get; set; }
        public  store store { get; set; }
    }
}
